### ISSUE TITLE
css classes minify

### ISSUE THREAD

**Issue by IndigoBee** [kangax/html-minifier#1086]
Can this plugin minify the css classes like this:

```css
.-pre-menu-post- {color: red;}
.-pre-menu_top-post- {color: black;}
.-pre-menu_item-post- {color: green;}
.-pre-menu_item_active-post- {color: blue;}
.-pre-menu_item_active-post-::before {content: 'active'}
```

Result
```css
.a0 {color: red;}
.a1 {color: black;}
.a2 {color: green;}
.a3 {color: blue;}
.a3::before {content: 'active'}
```
