### ISSUE TITLE
incorrectly removes whitespace before CSS wildcard selector

### ISSUE THREAD

**Issue by dwhieb** [kangax/html-minifier#1127]
In Elad Shechter's [new CSS reset](https://css-tricks.com/an-interview-with-elad-shechter-on-the-new-css-reset/), he uses the following lines of CSS:

```css
*:where(:not(iframe, canvas, img, svg, video):not(svg *)) {
  all: unset;
  display: revert;
}
```

html-minifier converts `:not(svg *)` to `:not(svg*)`, which is invalid CSS and prevents the rule from being applied.

I've confirmed that this error is _not_ caused by clean-css—it's caused by html-minifier.

I haven't been able to find any setting in html-minifier that I can adjust to fix this, except to use `ignoreCustomFragments`, which seems hacky.

It seems like html-minifier should not be removing whitespace in this instance.
